package common

func NewCodes() map[string]int {
	Codes := map[string]int{
		"break":     1,
		"default":   2,
		"fn":        3,
		"interface": 4,
		"const":     5,
		"case":      6,
		"struct":    7,
		"if":        8,
		"else":      9,
		"package":   10,
		"switch":    11,
		"goto":      12,
		"range":     13,
		"type":      14,
		"continue":  15,
		"for":       16,
		"return":    17,
		"import":    18,
		"var":       19,
		"+":         20,
		"-":         21,
		"*":         22,
		"/":         23,
		"(":         24,
		")":         25,
		"[":         26,
		"]":         27,
		"{":         28,
		"}":         29,
		"'":         30,
		",":         31,
		"<":         32,
		">":         33,
		"!":         34,
		":":         35,
		">=":        36,
		"<=":        37,
		"!=":        38,
		":=":        39,
		"=":         40,
		"==":        41,
		"&&":        42,
		"||":        43,
	}
	return Codes
}
